spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enhance
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

jwt:
  secret_key: 256qlxmfmfcndwhrtlzlrldnlgksxhzmsdkaghrkqtdlsepwjdakfrnlcksgek