spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/leetsEnhance
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  jwt:
    secret: ${JWT_SECRET_KEY}

logging.level:
  org.hibernate.SQL: debug
  org:
    springframework:
      security: debug
